// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbzdhe7uM-MY_HzFBLSwt2Iu8Dzo4Safk',
    appId: '1:960064319964:android:0933154185f214f9615f19',
    messagingSenderId: '960064319964',
    projectId: 'disectornew',
    storageBucket: 'disectornew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQUh3eA2lQ38Zo_KqWsd0zggj5tnVSaDE',
    appId: '1:960064319964:ios:9c42cf4485df4569615f19',
    messagingSenderId: '960064319964',
    projectId: 'disectornew',
    storageBucket: 'disectornew.appspot.com',
    androidClientId: '960064319964-944gs8r95gi6eg2kismmad2pjuqgus27.apps.googleusercontent.com',
    iosClientId: '960064319964-6e691drtlb4gldej0p8oqo3o6fl92c9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.pano1',
  );
}
